//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaCompanies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeltaCompaniesDBEntities : DbContext
    {
        public DeltaCompaniesDBEntities()
            : base("name=DeltaCompaniesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<ClientCorporation> ClientCorporations { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Placement> Placements { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TimedService> TimedServices { get; set; }
        public virtual DbSet<JobOrder> JobOrders { get; set; }
    }
}
